### ISSUE TITLE
Does it have to be a tool?

### ISSUE THREAD

**Issue by Madis0** [user11681/independent#1]
In order to do its job, does it have to be a tool that is ran before using the mods? Or could it also be used as a mod itself to prevent restrictions at runtime? If the former is the case, consider the latter a suggestion.

**Comment by user11681** [comment]
Yes, it has to be run on a directory or mod in order to have an effect. I can't make it a mod without modifying Fabric or it first being run alone and it then modifying the loader because by the time that a mod can execute any code, all mods are loaded and their dependencies are checked.

**Comment by user11681** [comment]
I might have not answered your question directly:
> In order to do its job, does it have to be a tool that is ran before using the mods?
Yes, because it reads their `fabric.mod.json` files, removes the `depends` blocks from them and then writes the changes to the files. So it must be used before Fabric is run.
